// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OBS_Projesi.Data;

#nullable disable

namespace OBS_Projesi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503193706_Baslangic")]
    partial class Baslangic
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OBS_Projesi.Models.Bolum", b =>
                {
                    b.Property<int>("BolumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BolumID"));

                    b.Property<string>("BolumAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BolumID");

                    b.ToTable("Bolum");
                });

            modelBuilder.Entity("OBS_Projesi.Models.Ders", b =>
                {
                    b.Property<int>("DersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersID"));

                    b.Property<int>("BolumID")
                        .HasColumnType("int");

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DersKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DersTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OgrenciSayisi")
                        .HasColumnType("int");

                    b.Property<int>("Yariyil")
                        .HasColumnType("int");

                    b.HasKey("DersID");

                    b.HasIndex("BolumID");

                    b.ToTable("Ders");
                });

            modelBuilder.Entity("OBS_Projesi.Models.Derslik", b =>
                {
                    b.Property<int>("DerslikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DerslikID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("bit");

                    b.Property<int>("Kapasite")
                        .HasColumnType("int");

                    b.Property<string>("Kat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DerslikID");

                    b.ToTable("Derslik");
                });

            modelBuilder.Entity("OBS_Projesi.Models.GozetmenAtama", b =>
                {
                    b.Property<int>("AtamaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AtamaID"));

                    b.Property<int>("PersonelID")
                        .HasColumnType("int");

                    b.Property<int>("SinavSalonuID")
                        .HasColumnType("int");

                    b.HasKey("AtamaID");

                    b.HasIndex("PersonelID");

                    b.HasIndex("SinavSalonuID");

                    b.ToTable("GozetmenAtama");
                });

            modelBuilder.Entity("OBS_Projesi.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciID"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PersonelID")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("KullaniciID");

                    b.HasIndex("PersonelID");

                    b.ToTable("Kullanici");
                });

            modelBuilder.Entity("OBS_Projesi.Models.Oturum", b =>
                {
                    b.Property<int>("OturumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OturumID"));

                    b.Property<TimeSpan>("BaslangicSaat")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("BitisSaat")
                        .HasColumnType("time");

                    b.Property<string>("Tanim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OturumID");

                    b.ToTable("Oturum");
                });

            modelBuilder.Entity("OBS_Projesi.Models.Personel", b =>
                {
                    b.Property<int>("PersonelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelID"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BolumID")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PersonelID");

                    b.HasIndex("BolumID");

                    b.ToTable("Personel");
                });

            modelBuilder.Entity("OBS_Projesi.Models.PersonelMazeret", b =>
                {
                    b.Property<int>("MazeretID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MazeretID"));

                    b.Property<string>("MazeretTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OturumID")
                        .HasColumnType("int");

                    b.Property<int>("PersonelID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UygunMu")
                        .HasColumnType("bit");

                    b.HasKey("MazeretID");

                    b.HasIndex("OturumID");

                    b.HasIndex("PersonelID");

                    b.ToTable("PersonelMazeret");
                });

            modelBuilder.Entity("OBS_Projesi.Models.Sinav", b =>
                {
                    b.Property<int>("SinavID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SinavID"));

                    b.Property<int>("DersID")
                        .HasColumnType("int");

                    b.Property<int>("OturumID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("SinavID");

                    b.HasIndex("DersID");

                    b.HasIndex("OturumID");

                    b.ToTable("Sinav");
                });

            modelBuilder.Entity("OBS_Projesi.Models.SinavLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("EskiDeger")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IslemTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PersonelID")
                        .HasColumnType("int");

                    b.Property<int>("SinavID")
                        .HasColumnType("int");

                    b.Property<string>("YeniDeger")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("LogID");

                    b.HasIndex("PersonelID");

                    b.HasIndex("SinavID");

                    b.ToTable("SinavLog");
                });

            modelBuilder.Entity("OBS_Projesi.Models.SinavSalonu", b =>
                {
                    b.Property<int>("SinavSalonuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SinavSalonuID"));

                    b.Property<int>("DerslikID")
                        .HasColumnType("int");

                    b.Property<int>("SinavID")
                        .HasColumnType("int");

                    b.HasKey("SinavSalonuID");

                    b.HasIndex("DerslikID");

                    b.HasIndex("SinavID");

                    b.ToTable("SinavSalonu");
                });

            modelBuilder.Entity("OBS_Projesi.Models.Ders", b =>
                {
                    b.HasOne("OBS_Projesi.Models.Bolum", "Bolum")
                        .WithMany("Dersler")
                        .HasForeignKey("BolumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolum");
                });

            modelBuilder.Entity("OBS_Projesi.Models.GozetmenAtama", b =>
                {
                    b.HasOne("OBS_Projesi.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OBS_Projesi.Models.SinavSalonu", "SinavSalonu")
                        .WithMany("GozetmenAtamalari")
                        .HasForeignKey("SinavSalonuID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("SinavSalonu");
                });

            modelBuilder.Entity("OBS_Projesi.Models.Kullanici", b =>
                {
                    b.HasOne("OBS_Projesi.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("OBS_Projesi.Models.Personel", b =>
                {
                    b.HasOne("OBS_Projesi.Models.Bolum", "Bolum")
                        .WithMany("Personeller")
                        .HasForeignKey("BolumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolum");
                });

            modelBuilder.Entity("OBS_Projesi.Models.PersonelMazeret", b =>
                {
                    b.HasOne("OBS_Projesi.Models.Oturum", "Oturum")
                        .WithMany()
                        .HasForeignKey("OturumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OBS_Projesi.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oturum");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("OBS_Projesi.Models.Sinav", b =>
                {
                    b.HasOne("OBS_Projesi.Models.Ders", "Ders")
                        .WithMany("Sinavlar")
                        .HasForeignKey("DersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OBS_Projesi.Models.Oturum", "Oturum")
                        .WithMany("Sinavlar")
                        .HasForeignKey("OturumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Oturum");
                });

            modelBuilder.Entity("OBS_Projesi.Models.SinavLog", b =>
                {
                    b.HasOne("OBS_Projesi.Models.Personel", "DegistirenPersonel")
                        .WithMany()
                        .HasForeignKey("PersonelID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OBS_Projesi.Models.Sinav", "Sinav")
                        .WithMany()
                        .HasForeignKey("SinavID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DegistirenPersonel");

                    b.Navigation("Sinav");
                });

            modelBuilder.Entity("OBS_Projesi.Models.SinavSalonu", b =>
                {
                    b.HasOne("OBS_Projesi.Models.Derslik", "Derslik")
                        .WithMany("SinavSalonlari")
                        .HasForeignKey("DerslikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OBS_Projesi.Models.Sinav", "Sinav")
                        .WithMany("SinavSalonlari")
                        .HasForeignKey("SinavID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Derslik");

                    b.Navigation("Sinav");
                });

            modelBuilder.Entity("OBS_Projesi.Models.Bolum", b =>
                {
                    b.Navigation("Dersler");

                    b.Navigation("Personeller");
                });

            modelBuilder.Entity("OBS_Projesi.Models.Ders", b =>
                {
                    b.Navigation("Sinavlar");
                });

            modelBuilder.Entity("OBS_Projesi.Models.Derslik", b =>
                {
                    b.Navigation("SinavSalonlari");
                });

            modelBuilder.Entity("OBS_Projesi.Models.Oturum", b =>
                {
                    b.Navigation("Sinavlar");
                });

            modelBuilder.Entity("OBS_Projesi.Models.Sinav", b =>
                {
                    b.Navigation("SinavSalonlari");
                });

            modelBuilder.Entity("OBS_Projesi.Models.SinavSalonu", b =>
                {
                    b.Navigation("GozetmenAtamalari");
                });
#pragma warning restore 612, 618
        }
    }
}
